# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

language: python
jobs:
  include:
    - name: Py3.6
      python: 3.6
      dist: bionic
    - name: Py3.7
      python: 3.7
      dist: focal
    - name: Py3.8
      python: 3.8
      dist: focal
    - name: Py2.7 (legacy)
      python: 2.7
      dist: xenial
cache: pip

addons:
  apt:
    packages:
      - vera++
      - libxml2-utils
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - openjdk-8-jre-headless
      - ant

env:
  # Need this environment if we're doing tests without a config file
  - READTHEDOCS=True

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  - support/rat.sh download
  # Bring pip up to date
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNStorageHandlers.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/PACMAN.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/DataSpecification.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/spalloc.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  # C dependencies
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinnaker_tools.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinn_common.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - export SPINN_DIRS=$PWD/spinnaker_tools

install:
  # Initialise builds against spinnaker_tools
  - make -C $SPINN_DIRS
  - make -C spinn_common install
  - make -C SpiNNFrontEndCommon/c_common install
  - pip install -r requirements-test.txt
  - pip install 'pylint<2.5' python-coveralls 'coverage>=4.4,<5.0'
  - python ./setup.py install

script:
  # Tests
  - py.test unittests --cov spinnaker_graph_front_end
  # Code quality check
  - flake8 spinnaker_graph_front_end
  - flake8 unittests
  - flake8 gfe_integration_tests
  # C
  - CFLAGS=-fdiagnostics-color make -C spinnaker_graph_front_end/examples
  - CFLAGS=-fdiagnostics-color make -C gfe_integration_tests
  # Copyright check
  - support/rat.sh run
  # Documentation build check
  - cd doc/source
  - sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  - sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  - sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
