#ifndef _GRAPH_FRONT_END_CONSTANTS_H_
#define _GRAPH_FRONT_END_CONSTANTS_H_

//! definitions of input components magic numbers

#define GRAPH_HEAT_ELEMENT_MAGIC_NUMBER 0xAD7
#define GRAPH_CELL_ELEMENT_MAGIC_NUMBER 0xAD8
#define GRAPH_PIXAL_ELEMENT_MAGIC_NUMBER 0xAD9

#endif // GRAPH_FRONT_END_CONSTANTS_H_