
# pacman imports
from pacman.model.partitioned_graph.partitioned_vertex import PartitionedVertex
from pacman.model.resources.cpu_cycles_per_tick_resource import \
    CPUCyclesPerTickResource
from pacman.model.constraints.placer_constraints\
    .placer_chip_and_core_constraint import PlacerChipAndCoreConstraint
from pacman.model.resources.dtcm_resource import DTCMResource
from pacman.model.resources.resource_container import ResourceContainer
from pacman.model.resources.sdram_resource import SDRAMResource

# GFE imports
from spinnaker_graph_front_end.utilities.conf import config

# fec imports
from spinn_front_end_common.utilities import constants
from spinn_front_end_common.abstract_models.\
    abstract_partitioned_data_specable_vertex \
    import AbstractPartitionedDataSpecableVertex
from spinn_front_end_common.utilities import exceptions

# dsg imports
from data_specification.data_specification_generator import \
    DataSpecificationGenerator

# general imports
from enum import Enum
import logging

logger = logging.getLogger(__name__)


class BranchVertex(PartitionedVertex, AbstractPartitionedDataSpecableVertex):
    """
    for handling a MST for communications.
    """

    DATA_REGIONS = Enum(
        value="DATA_REGIONS",
        names=[('SYSTEM', 0),
               ('SDP_PORT', 1)])

    SDP_PORT_MEMORY = 4

    def __init__(self, label, placement, sdp_port=4, machine_time_step=None,
                 time_scale_factor=None, constraints=None):

        sdram = ((constants.DATA_SPECABLE_BASIC_SETUP_INFO_N_WORDS + 3) * 4) \
                + self.SDP_PORT_MEMORY
        resources = ResourceContainer(cpu=CPUCyclesPerTickResource(45),
                                      dtcm=DTCMResource(100),
                                      sdram=SDRAMResource(sdram))

        # sort out machine time step
        if machine_time_step is None:
            self._machine_time_step = config.get("Machine", "machineTimeStep")
            if self._machine_time_step == "None":
                raise exceptions.ConfigurationException(
                    "Needs a machine time step that is not None, add to the "
                    "initiation or to a .spiNNakerGraphFrontEnd.cfg")
            else:
                self._machine_time_step = int(self._machine_time_step)
        else:
            self._machine_time_step = machine_time_step

        # sort out time scale factor
        if time_scale_factor is None:
            self._time_scale_factor = config.get("Machine", "timeScaleFactor")
            if self._time_scale_factor == "None":
                raise exceptions.ConfigurationException(
                    "Needs a time scale factor that is not None, add to the "
                    "initiation or to a .spiNNakerGraphFrontEnd.cfg")
            else:
                self._time_scale_factor = int(self._time_scale_factor)
        else:
            self._time_scale_factor = time_scale_factor

        PartitionedVertex.__init__(
            self, label=label, resources_required=resources,
            constraints=constraints)
        AbstractPartitionedDataSpecableVertex.__init__(
            self, machine_time_step=self._machine_time_step,
            timescale_factor=self._time_scale_factor)

        x, y, p = placement
        self._sdp_port = sdp_port
        self.add_constraint(PlacerChipAndCoreConstraint(x, y, p))

    def get_binary_file_name(self):
        """
        binary name
        :return:
        """
        return "branch.aplx"

    def model_name(self):
        """
        human readable name
        :return:
        """
        return "BranchVertex"

    def generate_data_spec(
            self, placement, sub_graph, routing_info, hostname, report_folder,
            ip_tags, reverse_ip_tags, write_text_specs,
            application_run_time_folder):
        """
        method to determine how to generate their data spec for a non neural
        application

        :param placement: the placement object for the dsg
        :param sub_graph: the partitioned graph object for this dsg
        :param routing_info: the routing info object for this dsg
        :param hostname: the machines hostname
        :param ip_tags: the collection of iptags generated by the tag allocator
        :param reverse_ip_tags: the collection of reverse iptags generated by
        the tag allocator
        :param report_folder: the folder to write reports to
        :param write_text_specs: bool which says if test specs should be written
        :param application_run_time_folder: the folder where application files
         are written
        """

        data_writer, report_writer = \
            self.get_data_spec_file_writers(
                placement.x, placement.y, placement.p, hostname, report_folder,
                write_text_specs, application_run_time_folder)

        spec = DataSpecificationGenerator(data_writer, report_writer)

        # Setup words + 1 for flags + 1 for recording size
        setup_size = (constants.DATA_SPECABLE_BASIC_SETUP_INFO_N_WORDS + 3) * 4

        # Reserve SDRAM space for memory areas:

        # Create the data regions for hello world
        self._reserve_memory_regions(spec, setup_size)
        self._write_basic_setup_info(spec, self.DATA_REGIONS.SYSTEM.value)

        # write sdp port
        self._write_sdp_port(spec)

        # End-of-Spec:
        spec.end_specification()

        # close writer
        data_writer.close()

        # return file path for data
        return data_writer.filename

    def _reserve_memory_regions(self, spec, system_size):
        """
        *** Modified version of same routine in abstract_models.py These could
        be combined to form a common routine, perhaps by passing a list of
        entries. ***
        Reserve memory for the system, indices and spike data regions.
        The indices region will be copied to DTCM by the executable.
        :param spec:
        :param system_size:
        :return:
        """
        spec.reserve_memory_region(region=self.DATA_REGIONS.SYSTEM.value,
                                   size=system_size, label='systemInfo')
        spec.reserve_memory_region(region=self.DATA_REGIONS.SDP_PORT.value,
                                   size=self.SDP_PORT_MEMORY, label="SDP_PORT")

    def _write_sdp_port(self, spec):
        """
        writes the sdp port number for c configuration
        :param spec: the spec to write
        :return: None
        """
        spec.switch_write_focus(self.DATA_REGIONS.SDP_PORT.value)
        spec.write_value(self._sdp_port)

    def is_partitioned_data_specable(self):
        """
        helper method for isinstance
        :return:
        """
        return True
